### ISSUE TITLE
Sub Generator Failing Tests in Travis

### ISSUE THREAD

**Issue by afj176** [afj176/generator-mongoose#17]
1) mongoose generator creates expected files:
     Uncaught TypeError: object is not a function
      at MongooseGenerator.<anonymous> (/home/travis/build/afj176/generator-mongoose/node_modules/yeoman-generator/lib/base.js:383:5)

2) mongoose generator mongoose schema generator creates expected files:
     Uncaught TypeError: object is not a function
      at SchemaGenerator.<anonymous> (/home/travis/build/afj176/generator-mongoose/node_modules/yeoman-generator/lib/base.js:383:5)

**Comment by afj176** [comment]
fixed
