### ISSUE TITLE
Cannot call method 'slugify' of undefined

### ISSUE THREAD

**Issue by leandono** [afj176/generator-mongoose#19]
Hi, 
When I run the generator, in the step "Will you be using heroku?" I have this error:

```
? Will you be using heroku? No
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #_ is deprecated. Require your own version of Lodash or underscore.string

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot call method 'slugify' of undefined
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/node_modules/lodash/index.js:10693:16), <anonymous>:8:13)
    at underscore (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/lib/util/engines.js:23:45)
    at MongooseGenerator.actions.engine (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/lib/actions/actions.js:224:32)
    at MongooseGenerator.template (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/lib/actions/actions.js:198:19)
    at MongooseGenerator.app (/usr/local/lib/node_modules/generator-mongoose/app/index.js:76:8)
    at /usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/lib/base.js:421:16
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

I think that is related with this issue: https://github.com/yeoman/generator/issues/766

**Comment by afj176** [comment]
I will look into this, will have a fix for this tonight.
Thanks!

**Comment by arvindr21** [comment]
While installing the generator

```shell
$  npm install -g generator-mongoose
npm WARN peerDependencies The peer dependency yo@>=1.4.x included from generator-mongoose will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
generator-mongoose@1.1.1 /usr/local/lib/node_modules/generator-mongoose
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, has-ansi@1.0.3, strip-ansi@2.0.1)
├── request@2.55.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.6.1, stringstream@0.0.4, tunnel-agent@0.4.0, oauth-sign@0.6.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.4.1, form-data@0.2.0, combined-stream@0.0.7, bl@0.9.4, mime-types@2.0.10, http-signature@0.10.1, tough-cookie@1.0.0, hawk@2.3.1, har-validator@1.6.1)
└── yeoman-generator@0.19.2 (read-chunk@1.0.1, detect-conflict@1.0.0, dargs@4.0.0, yeoman-welcome@1.0.1, xdg-basedir@1.0.1, user-home@1.1.1, diff@1.3.2, text-table@0.2.0, mime@1.3.4, async@0.9.0, shelljs@0.4.0, underscore.string@3.0.3, cross-spawn@0.2.9, lodash@3.7.0, cli-table@0.3.1, debug@2.1.3, istextorbinary@1.0.2, nopt@3.0.1, through2@0.6.5, run-async@0.1.0, mem-fs-editor@1.2.3, sinon@1.14.1, mkdirp@0.5.0, pretty-bytes@1.0.4, dateformat@1.0.11, github-username@1.1.1, glob@5.0.5, findup-sync@0.2.1, rimraf@2.3.2, yeoman-assert@1.0.0, class-extend@0.1.1, yeoman-environment@1.2.5, inquirer@0.8.2, html-wiring@1.1.0, gruntfile-editor@1.0.0, download@4.1.2)
```

error stack when running the installer with a No for heroku (`genmon` is the name of folder I am scaffolding in)

```shell
 $ genmon  yo mongoose
(!) this.readFileAsString() is deprecated. Use require("html-wiring").readFileAsString() instead.

 .--------------------------.
 |      mongoose:app        |
 .__________________________.


? Database Name: myDb
? Database Host: localhost
? Database User: 
? Database Password: 
? Database Port: 27017
? Will you be using heroku? No
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #_ is deprecated. Require your own version of Lodash or underscore.string
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'slugify' of undefined
    at eval (lodash.templateSources[1]:9:12)
    at underscore (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/lib/util/engines.js:23:45)
    at MongooseGenerator.actions.engine (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/lib/actions/actions.js:224:32)
    at MongooseGenerator.template (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/lib/actions/actions.js:198:19)
    at MongooseGenerator.app (/usr/local/lib/node_modules/generator-mongoose/app/index.js:76:8)
    at /usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/lib/base.js:421:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

```shell
$ yo --version
1.4.6
```

**Comment by afj176** [comment]
Just wanted to keep you up to date, found the changes I need to make, will be making them later today.

**Comment by afj176** [comment]
@leandono & @arvindr21 Thanks for the help, this is resolved.
