### ISSUE TITLE
Errors upon when generating

### ISSUE THREAD

**Issue by mimiflynn** [afj176/generator-mongoose#20]
I'm getting the following error before the questions right after running `yo mongoose`:

```
(!) this.readFileAsString() is deprecated. Use require("html-wiring").readFileAsString() instead.
```

I'm also getting errors after answering the initialization questions:

```
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
events.js:85
      throw er; // Unhandled 'error' event
            ^
ReferenceError: /usr/local/lib/node_modules/generator-mongoose/app/templates/Gruntfile.js:45
    43|     open: {
    44|       server: {
 >> 45|         url: 'http://localhost:<%= express.options.port %>'
    46|       }
    47|     }
    48|   });

express is not defined
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:455:12), <anonymous>:11:28)
    at /usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:482:14
    at Object.exports.render (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:316:13)
    at copy.process (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:18:18)
    at applyProcessingFunc (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:12:16)
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:55:24)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:22:17)
    at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:16:8)
    at MongooseGenerator.template (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/lib/actions/actions.js:134:11)
    at MongooseGenerator.copy (/usr/local/lib/node_modules/generator-mongoose/node_modules/yeoman-generator/lib/actions/actions.js:43:10)
```

I answered the questions as follows:

```
? Database Name: contacts-react
? Database Host: localhost
? Database User:
? Database Password:
? Database Port: 27017
? Will you be using heroku? No
```

**Comment by afj176** [comment]
What version of npm and node are you using, I would like try to recreate the issue.

**Comment by mimiflynn** [comment]
Node is 0.12.2 and NPM is 2.7.5

I fixed the `mkdir` and `readFileAsString` deprecation issues [here](https://github.com/mimiflynn/generator-mongoose/commit/d6fff47c1264e7d166854c7ebea8a3b7a348ad78) and am now getting errors with the `index.html`:

```
ReferenceError: /Users/mimiflynn/Projects/generator-mongoose/app/templates/views/index.html:11
    9|       <div class="container">
    10|         <div class="navbar-header">
 >> 11|           <a class="navbar-brand" href="javascript:"><%= siteName %></a>
    12|         </div>
    13|       </div>
    14|     </div>

siteName is not defined
    at eval (eval at <anonymous> (/Users/mimiflynn/Projects/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:455:12), <anonymous>:11:28)
    at /Users/mimiflynn/Projects/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:482:14
    at Object.exports.render (/Users/mimiflynn/Projects/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:316:13)
    at copy.process (/Users/mimiflynn/Projects/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:18:18)
    at applyProcessingFunc (/Users/mimiflynn/Projects/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:12:16)
    at EditionInterface.exports._copySingle (/Users/mimiflynn/Projects/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:55:24)
    at EditionInterface.exports.copy (/Users/mimiflynn/Projects/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:22:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/mimiflynn/Projects/generator-mongoose/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:16:8)
    at MongooseGenerator.template (/Users/mimiflynn/Projects/generator-mongoose/node_modules/yeoman-generator/lib/actions/actions.js:134:11)
    at MongooseGenerator.copy (/Users/mimiflynn/Projects/generator-mongoose/node_modules/yeoman-generator/lib/actions/actions.js:43:10)
```

**Comment by afj176** [comment]
On one computer I am running 
node v0.10.36
npm 2.8.4
On another I am running:
node v0.12.3
npm 2.9.1
I couldn't recreate the issue.

@arvindr21 can you try to recreate this issue? What version of node and npm are you on?

@mimiflynn Can you update your npm?

**Comment by hanhanx** [comment]
Node: v0.12.0
npm: 2.10.0
I'm getting the same issue.

**Comment by afj176** [comment]
hmmm, what version of yo is everyone using?
I am using yo@1.4.6

**Comment by afj176** [comment]
Ok I was able to recreate it.
Working on a fix now.
I was npm linked local to the module and was getting different results.
Will have solution soon, thanks everyone.

**Comment by hanhanx** [comment]
yo@1.4.6

**Comment by afj176** [comment]
@mimiflynn & @hanhanx let me know if all is good.
